export const profileData = {
  name: 'Sourav Sarkar',
  title: 'UI/UX Designer',
  avatar: '/profile.png',
  email: 'workwith.akash26@gmail.com',
  phone: '+880 1608-175433',
  resume: 'Download',
  location: 'Barisal, Bangladesh',
  resumeUrl: '/resume.pdf',
  social: {
    github: 'https://github.com/johndoe',
    twitter: 'https://twitter.com/johndoe',
    instagram: 'https://instagram.com/johndoe',
  },
}

export const aboutData = {
  description: [
    "I'm a passionate UI/UX designer with over 2 years of experience in crafting intuitive and visually appealing digital experiences. I specialize in creating user-centered designs that not only look great but also provide seamless functionality. My expertise lies in understanding user needs, conducting research, and translating insights into innovative design solutions that drive engagement and satisfaction. I have a strong background in design tools such as Figma, Sketch, and Adobe Creative Suite, and I stay up-to-date with the latest design trends and best practices. \n\nI thrive in collaborative environments where I can work closely with developers, product managers, and stakeholders to bring ideas to life. My goal is to create designs that not only meet business objectives but also delight users and enhance their overall experience. I am always eager to take on new challenges and contribute my skills to create impactful digital products that make a difference. I am excited to continue growing as a designer and to work on projects that push the boundaries of creativity and innovation. \n\nI am committed to delivering high-quality designs that exceed expectations and drive meaningful results for both users and businesses.",
  ],
  services: [
    {
      icon: 'PenTool',
      title: 'User-Centered Thinking',
      description: 'Always design with the end-user in mind. Understand their needs, behaviors, and pain points through research and usability testing. A beautiful interface means little if it doesn’t solve the user’s problem.',
    },
    {
      icon: 'Code',
      title: 'Strong Visual & Interaction Design',
      description: 'Master typography, color theory, spacing, and layout. Combine aesthetics with functionality—your designs should not only look good but also guide users intuitively through interactions.',
    },
    {
      icon: 'Smartphone',
      title: 'Prototyping & Iteration',
      description: 'Use tools like Figma, Adobe XD, or Sketch to create wireframes and interactive prototypes. Test early, gather feedback, and refine continuously. Iteration is the backbone of great UX.',
    },
    {
      icon: 'Zap',
      title: 'Collaboration & Communication',
      description: 'Work closely with developers, product managers, and stakeholders. Being able to explain design decisions clearly and advocate for the user experience is just as important as the design itself.',
    },
  ],
  testimonials: [
    {
      avatar: '/professional-man.jpg',
      name: 'Daniel Lewis',
      text: 'Sourav is an exceptional designer who consistently delivers high-quality work. His ability to understand user needs and translate them into beautiful, functional designs is impressive. He’s a pleasure to work with and always goes above and beyond to ensure client satisfaction.',
    },
    {
      avatar: '/professional-woman-diverse.png',
      name: 'Jessica Miller',
      text: 'Sourav is an exceptional designer who consistently delivers high-quality work. His ability to understand user needs and translate them into beautiful, functional designs is impressive. He’s a pleasure to work with and always goes above and beyond to ensure client satisfaction.',
    },
    {
      avatar: '/professional-man.jpg',
      name: 'Michael Chen',
      text: 'Sourav is a talented designer with a keen eye for detail. He has a deep understanding of user experience principles and consistently creates designs that are both visually stunning and highly usable. His professionalism and dedication make him an invaluable asset to any project.',
    },
    {
      avatar: '/professional-woman-diverse.png',
      name: 'Sarah Johnson',
      text: 'Sourav is a fantastic designer who brings creativity and innovation to every project. His ability to empathize with users and create designs that truly resonate with them is remarkable. He’s a great collaborator and always delivers work that exceeds expectations.',
    },
  ],
  clients: [
    { name: 'TechCorp', logo: '/tech-company-logo.jpg' },
    { name: 'StartupHub', logo: '/startup-logo.png' },
    { name: 'DesignStudio', logo: '/design-agency-logo.png' },
    { name: 'CodeLabs', logo: '/software-company-logo.png' },
    { name: 'WebSolutions', logo: '/web-agency-logo.jpg' },
    { name: 'AppMakers', logo: '/app-development-logo.jpg' },
  ],
}

export const resumeData = {
  education: [
    {
      title: 'Computer Science and Engineering',
      institution: 'Patuakhali Polytechnic Institute',
      period: '2021 - 2022',
      description:
        'Completed a comprehensive Computer Science and Engineering program with a focus on software development, algorithms, and data structures. Gained hands-on experience through projects and internships, developing a strong foundation in programming languages such as Java, Python, and C++. Graduated with honors and received recognition for outstanding academic performance.',
    },
    {
      title: 'UI/UX Design Course',
      institution: 'BDCalling Academy',
      period: 'September - December, 2025',
      description: 'Completed an intensive UI/UX design course covering user research, wireframing, prototyping, and visual design principles. Developed a portfolio of design projects that demonstrate a strong understanding of user-centered design and best practices in the industry.',
    },
  ],
  experience: [
    {
      title: 'Junior UI/UX Designer',
      company: 'MNTech Digital',
      period: 'April 2026 - Present',
      description:
        'Collaborate with cross-functional teams to design user interfaces for web and mobile applications. Conduct user research and usability testing to inform design decisions. Create wireframes, prototypes, and high-fidelity designs using Figma and Adobe XD. Contribute to the development of design systems and style guides to ensure consistency across products.',
    },
    {
      title: 'UI/UX Designer (Intern)',
      company: 'Bdcalling IT Ltd.',
      period: 'January - March, 2026',
      description:
        'Collaborated on designing user interfaces for mobile and web applications. Conducted user research and usability testing to inform design decisions. Created wireframes, prototypes, and high-fidelity designs using Figma and Adobe XD.',
    },
  ],
  skills: [
    { name: 'UI/UX Design', level: 85 },
    { name: 'UX Research', level: 80 },
    { name: 'UX Strategy', level: 75 },
    { name: 'UX Writing', level: 80 },
    { name: 'User Testing', level: 75 },
    { name: 'Design Systems', level: 80 },
    { name: 'Prototyping', level: 85 },
    { name: 'Wireframing', level: 80 },
    { name: 'Figma, Adobe XD, Sketch', level: 90 },
    { name: 'HTML, CSS, JavaScript', level: 20 },
    { name: 'Project Management', level: 70 },
    { name: 'Time Management', level: 90 },
    { name: 'Communication', level: 75 },
    { name: 'Problem Solving', level: 80 },
    { name: 'Adaptability', level: 95 },
    { name: 'Leadership', level: 50 },
    { name: 'Teamwork', level: 90 },
    { name: 'Creativity', level: 90 },
    { name: 'Critical Thinking', level: 85 },
  ],
}

export const portfolioData = {
  categories: ['all', 'website design', 'app design', 'dashboard design'],
  projects: [
    {
      title: 'E-Commerce Platform',
      category: 'website design',
      image: '/modern-ecommerce-website.png',
      description: 'Design and development of a modern e-commerce platform with seamless user experience',
      tech: ['Next.js', 'Tailwind CSS', 'Stripe API'],
      liveUrl: 'https://example.com',
      githubUrl: 'https://behnace.net/',
    },
    {
      title: 'Task Management App',
      category: 'app design',
      image: '/task-management-interface.png',
      description: 'Intuitive task management app with drag-and-drop functionality and collaboration features',
      tech: ['React Native', 'Redux', 'Firebase'],
      liveUrl: 'https://example.com',
      githubUrl: 'https://behnace.net/',
    },
    {
      title: 'Portfolio Website',
      category: 'website design',
      image: '/minimalist-portfolio-design.jpg',
      description: 'Personal portfolio website showcasing design projects and case studies',
      tech: ['Gatsby', 'Styled Components', 'GraphQL'],
      liveUrl: 'https://example.com',
      githubUrl: 'https://behnace.net/',
    },
    {
      title: 'Social Media Dashboard',
      category: 'dashboard design',
      image: '/analytics-dashboard.png',
      description: 'Comprehensive social media analytics dashboard with real-time data visualization',
      tech: ['React', 'D3.js', 'Node.js'],
      liveUrl: 'https://example.com',
      githubUrl: 'https://behnace.net/',
    },
    {
      title: 'Task Management App',
      category: 'app design',
      image: '/task-management-interface.png',
      description: 'Intuitive task management app with drag-and-drop functionality and collaboration features',
      tech: ['React Native', 'Redux', 'Firebase'],
      liveUrl: 'https://example.com',
      githubUrl: 'https://behnace.net/',
    },
    {
      title: 'Portfolio Website',
      category: 'website design',
      image: '/minimalist-portfolio-design.jpg',
      description: 'Personal portfolio website showcasing design projects and case studies',
      tech: ['Gatsby', 'Styled Components', 'GraphQL'],
      liveUrl: 'https://example.com',
      githubUrl: 'https://behnace.net/',
    },
    {
      title: 'Task Management App',
      category: 'app design',
      image: '/task-management-interface.png',
      description: 'Intuitive task management app with drag-and-drop functionality and collaboration features',
      tech: ['React Native', 'Redux', 'Firebase'],
      liveUrl: 'https://example.com',
      githubUrl: 'https://behnace.net/',
    },
    {
      title: 'Portfolio Website',
      category: 'website design',
      image: '/minimalist-portfolio-design.jpg',
      description: 'Personal portfolio website showcasing design projects and case studies',
      tech: ['Gatsby', 'Styled Components', 'GraphQL'],
      liveUrl: 'https://example.com',
      githubUrl: 'https://behnace.net/',
    },
    {
      title: 'Social Media Dashboard',
      category: 'dashboard design',
      image: '/analytics-dashboard.png',
      description: 'Comprehensive social media analytics dashboard with real-time data visualization',
      tech: ['React', 'D3.js', 'Node.js'],
      liveUrl: 'https://example.com',
      githubUrl: 'https://behnace.net/',
    },{
      title: 'Task Management App',
      category: 'app design',
      image: '/task-management-interface.png',
      description: 'Intuitive task management app with drag-and-drop functionality and collaboration features',
      tech: ['React Native', 'Redux', 'Firebase'],
      liveUrl: 'https://example.com',
      githubUrl: 'https://behnace.net/',
    },
    {
      title: 'Portfolio Website',
      category: 'website design',
      image: '/minimalist-portfolio-design.jpg',
      description: 'Personal portfolio website showcasing design projects and case studies',
      tech: ['Gatsby', 'Styled Components', 'GraphQL'],
      liveUrl: 'https://example.com',
      githubUrl: 'https://behnace.net/',
    },
    {
      title: 'Social Media Dashboard',
      category: 'dashboard design',
      image: '/analytics-dashboard.png',
      description: 'Comprehensive social media analytics dashboard with real-time data visualization',
      tech: ['React', 'D3.js', 'Node.js'],
      liveUrl: 'https://example.com',
      githubUrl: 'https://behnace.net/',
    },
    {
      title: 'Social Media Dashboard',
      category: 'dashboard design',
      image: '/analytics-dashboard.png',
      description: 'Comprehensive social media analytics dashboard with real-time data visualization',
      tech: ['React', 'D3.js', 'Node.js'],
      liveUrl: 'https://example.com',
      githubUrl: 'https://behnace.net/',
    },
    {
      title: 'Mobile Banking App',
      category: 'app design',
      image: '/banking-app-interface.png',
      description: 'Secure and user-friendly mobile banking app with features like account management, fund transfers, and bill payments',
      tech: ['React Native', 'Node.js', 'MongoDB'],
      liveUrl: 'https://example.com',
      githubUrl: 'https://behnace.net/',
    },
    {
      title: 'Restaurant Website',
      category: 'website design',
      image: '/restaurant-website-design.png',
      description: 'Visually appealing restaurant website with online reservation and menu browsing features',
      tech: ['Next.js', 'Tailwind CSS', 'Contentful CMS'],
      liveUrl: 'https://example.com',
      githubUrl: 'https://behnace.net/',
    },
  ],
}

export const blogData = {
  posts: [
    {
      title: 'UI/UX Design Trends to Watch in 2024',
      category: 'Design',
      date: 'Mar 15, 2026',
      readTime: '8 min',
      image: '/web-development-coding.png',
      excerpt: 'Explore the latest UI/UX design trends that are shaping the digital landscape in 2024.',
      tags: ['Design', 'UI/UX', 'Trends'],
      slug: 'ui-ux-design-trends-2024',
    },
    {
      title: 'Microservices Architecture: A Complete Guide',
      category: 'Architecture',
      date: 'Mar 8, 2024',
      readTime: '12 min',
      image: '/software-architecture.jpg',
      excerpt: 'Design scalable microservices with real-world examples.',
      tags: ['Architecture', 'Backend', 'DevOps'],
      slug: 'microservices-architecture-guide',
    },
    {
      title: 'The Art of UI/UX: Creating Delightful Experiences',
      category: 'Design',
      date: 'Feb 28, 2024',
      readTime: '6 min',
      image: '/ui-ux-design-concept.png',
      excerpt: 'Principles of exceptional UI/UX design for interfaces users love.',
      tags: ['Design', 'UI/UX', 'Frontend'],
      slug: 'art-of-uiux-delightful-experiences',
    },
    {
      title: 'UI/UX Design Trends to Watch in 2024',
      category: 'Design',
      date: 'Mar 15, 2026',
      readTime: '8 min',
      image: '/web-development-coding.png',
      excerpt: 'Explore the latest UI/UX design trends that are shaping the digital landscape in 2024.',
      tags: ['Design', 'UI/UX', 'Trends'],
      slug: 'ui-ux-design-trends-2024',
    },
    {
      title: 'Microservices Architecture: A Complete Guide',
      category: 'Architecture',
      date: 'Mar 8, 2024',
      readTime: '12 min',
      image: '/software-architecture.jpg',
      excerpt: 'Design scalable microservices with real-world examples.',
      tags: ['Architecture', 'Backend', 'DevOps'],
      slug: 'microservices-architecture-guide',
    },
    {
      title: 'The Art of UI/UX: Creating Delightful Experiences',
      category: 'Design',
      date: 'Feb 28, 2024',
      readTime: '6 min',
      image: '/ui-ux-design-concept.png',
      excerpt: 'Principles of exceptional UI/UX design for interfaces users love.',
      tags: ['Design', 'UI/UX', 'Frontend'],
      slug: 'art-of-uiux-delightful-experiences',
    },
    {
      title: 'UI/UX Design Trends to Watch in 2024',
      category: 'Design',
      date: 'Mar 15, 2026',
      readTime: '8 min',
      image: '/web-development-coding.png',
      excerpt: 'Explore the latest UI/UX design trends that are shaping the digital landscape in 2024.',
      tags: ['Design', 'UI/UX', 'Trends'],
      slug: 'ui-ux-design-trends-2024',
    },
    {
      title: 'Microservices Architecture: A Complete Guide',
      category: 'Architecture',
      date: 'Mar 8, 2024',
      readTime: '12 min',
      image: '/software-architecture.jpg',
      excerpt: 'Design scalable microservices with real-world examples.',
      tags: ['Architecture', 'Backend', 'DevOps'],
      slug: 'microservices-architecture-guide',
    },
    {
      title: 'UI/UX Design Trends to Watch in 2024',
      category: 'Design',
      date: 'Mar 15, 2026',
      readTime: '8 min',
      image: '/web-development-coding.png',
      excerpt: 'Explore the latest UI/UX design trends that are shaping the digital landscape in 2024.',
      tags: ['Design', 'UI/UX', 'Trends'],
      slug: 'ui-ux-design-trends-2024',
    },
    {
      title: 'Microservices Architecture: A Complete Guide',
      category: 'Architecture',
      date: 'Mar 8, 2024',
      readTime: '12 min',
      image: '/software-architecture.jpg',
      excerpt: 'Design scalable microservices with real-world examples.',
      tags: ['Architecture', 'Backend', 'DevOps'],
      slug: 'microservices-architecture-guide',
    },
    {
      title: 'The Art of UI/UX: Creating Delightful Experiences',
      category: 'Design',
      date: 'Feb 28, 2024',
      readTime: '6 min',
      image: '/ui-ux-design-concept.png',
      excerpt: 'Principles of exceptional UI/UX design for interfaces users love.',
      tags: ['Design', 'UI/UX', 'Frontend'],
      slug: 'art-of-uiux-delightful-experiences',
    },
    {
      title: 'The Art of UI/UX: Creating Delightful Experiences',
      category: 'Design',
      date: 'Feb 28, 2024',
      readTime: '6 min',
      image: '/ui-ux-design-concept.png',
      excerpt: 'Principles of exceptional UI/UX design for interfaces users love.',
      tags: ['Design', 'UI/UX', 'Frontend'],
      slug: 'art-of-uiux-delightful-experiences',
    },
    {
      title: 'UX Research Methods: A Comprehensive Overview',
      category: 'Design',
      date: 'Feb 20, 2024',
      readTime: '10 min',
      image: '/web-development-coding.png',
      excerpt: 'In-depth look at UX research techniques to understand user behavior and inform design decisions.',
      tags: ['UX Research', 'Design', 'User Experience'],
      slug: 'ux-research-methods-comprehensive-overview',
    },
    {
      title: 'Real-Time Applications with WebSockets',
      category: 'Development',
      date: 'Feb 12, 2024',
      readTime: '9 min',
      image: '/software-architecture.jpg',
      excerpt: 'Implement real-time features using WebSockets and modern frameworks.',
      tags: ['WebSockets', 'Real-time', 'Backend'],
      slug: 'realtime-apps-websockets',
    },
    {
      title: 'Mastering CSS Grid and Flexbox Layouts',
      category: 'Design',
      date: 'Feb 5, 2024',
      readTime: '7 min',
      image: '/ui-ux-design-concept.png',
      excerpt: 'Comprehensive guide to creating responsive layouts with CSS Grid and Flexbox.',
      tags: ['CSS', 'Layout', 'Frontend'],
      slug: 'mastering-css-grid-flexbox',
    },
  ],
}

export const contactData = {
  email: 'workwith.akash26@gmail.com',
  phone: '+880 1608-175433',
  location: 'Barisal, Bangladesh',
  mapEmbedUrl:
    'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d100940.14220298434!2d-122.50764017406082!3d37.75767381338211!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80859a6d00690021%3A0x4a501367f076adff!2sSan%20Francisco%2C%20CA%2C%20USA!5e0!3m2!1sen!2sus!4v1234567890123!5m2!1sen!2sus',
}
